--MEMBUAT TABLE EMPLOYEE, SCRIPT INI MENGGUNAKAN DATABASE ORACLE
--SELECT * FROM EMPLOYEE
/* JAWABAN NO 1 */
CREATE TABLE EMPLOYEE (
    ID NUMBER NOT NULL,
    EMPLOYEE_ID VARCHAR2(10) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    ADDRESS VARCHAR(500) ,
    CONSTRAINT UNIK_ID UNIQUE (EMPLOYEE_ID),
    CONSTRAINT PK_ID PRIMARY KEY (ID)
    );    
    
--SELECT * FROM POSITION_HISTORY
--MEMBUAT TABLE POSITION_HISTORY
CREATE TABLE POSITION_HISTORY (
    ID NUMBER NOT NULL,
    POS_ID  VARCHAR2(10),
    POS_TITLE VARCHAR2(100) NOT NULL,
    EMPLOYEE_ID VARCHAR2(10) NOT NULL,
    START_DATE DATE NOT NULL ,
    END_DATE DATE NOT NULL,
    CONSTRAINT PK_ID_POS PRIMARY KEY (ID)
    );

/* JAWABAN NO 2 */

--MENGISI DATA TABEL EMPLOYEE
INSERT INTO EMPLOYEE (ID, EMPLOYEE_ID,FULL_NAME,BIRTHDATE,ADDRESS)
VALUES (1, 10105001, 'Ali Anton', '19-Aug-82', 'JAKARTA UTARA');

INSERT INTO EMPLOYEE (ID, EMPLOYEE_ID,FULL_NAME,BIRTHDATE,ADDRESS)
VALUES (2, 10105002, 'Rara Siva', '1-Jan-82', 'Mandalika');

INSERT INTO EMPLOYEE (ID, EMPLOYEE_ID,FULL_NAME,BIRTHDATE,ADDRESS)
VALUES (3, 10105003, 'Rini Aini', '20-Feb-82', 'Sumbawa Besar');

INSERT INTO EMPLOYEE (ID, EMPLOYEE_ID,FULL_NAME,BIRTHDATE,ADDRESS)
VALUES (4, 10105004, 'Budi', '22-Feb-82', 'Mataram Kota');
    
    
 --MENGISI DATA TABEL POSITION_HISTORY    
INSERT INTO POSITION_HISTORY
VALUES ( 1,5000 ,' IT Manager', 10105001,' 1-Jan-2022',' 28-Feb-2022');

INSERT INTO POSITION_HISTORY
VALUES ( 2 ,50001,' IT Sr. Manager', 10105001,' 1-Mar-2022',' 31-Dec-2022');

INSERT INTO POSITION_HISTORY
VALUES ( 3, 50002,'Programmer Analyst', 10105002,' 1-Jan-2022','28-Feb-2022');

INSERT INTO POSITION_HISTORY
VALUES ( 4, 50003, 'Sr. Programmer Analyst', 10105002,'1-Mar-2022', '31-Dec-2022');

INSERT INTO POSITION_HISTORY
VALUES ( 5, 50004, 'IT Admin', 10105003 ,'1-Jan-2022', '28-Feb-2022');

INSERT INTO POSITION_HISTORY
VALUES (6, 50005, 'IT Secretary' , 10105003, '1-Mar-2022', '31-Dec-2022');


/* JAWABAN NO 3 */
--SELECT * FROM EMPLOYEE --SELECT * FROM POSITION_HISTORY
SELECT  E.EMPLOYEE_ID, E.FULL_NAME, E.BIRTHDATE, E.ADDRESS,
        P.POS_ID, P.POS_TITLE, P.EMPLOYEE_ID, P.START_DATE, P.END_DATE
FROM EMPLOYEE E
INNER JOIN POSITION_HISTORY P
ON E.ID = P.ID





